name: Release

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  release:
    if: contains(github.event.head_commit.message, 'release-please--branches') || startsWith(github.event.head_commit.message, 'bump')
    runs-on: ubuntu-latest

    steps:
      # Generate a token for `release-please`
      - name: Generate GitHub App Token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PEM }}

      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      # Build the Spring Boot application
      - name: Build Spring Boot Application
        run: |
          mvn clean package
          ls -la target/

      # Run `release-please` to create changelog and GitHub release
      - name: Release with Release Please
        uses: googleapis/release-please-action@v4
        id: release
        with:
          token: "${{ steps.generate_token.outputs.token }}"
          manifest-file: .release-please-manifest.json
          config-file: release-please-config.json
